--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-03-15 03:09:40

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 37986)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    role character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 37985)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 37991)
-- Name: user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_role (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_role OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 37994)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    cin character varying(255),
    email character varying(255),
    firstname character varying(255),
    lastname character varying(255),
    password character varying(255),
    archiver boolean,
    force_change_password boolean
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 37984)
-- Name: users_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_seq OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 38004)
-- Name: verfication_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verfication_token (
    is_verified boolean NOT NULL,
    expiration_time timestamp(6) without time zone,
    id bigint NOT NULL,
    user_id bigint,
    token character varying(255)
);


ALTER TABLE public.verfication_token OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 38003)
-- Name: verfication_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.verfication_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verfication_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4918 (class 0 OID 37986)
-- Dependencies: 219
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (role_id, role) FROM stdin;
1	ROLE_ADMIN
2	ROLE_RES_COMERCIAL
3	ROLE_RES_ACHAT
4	ROLE_RES_FINANCEMENT
5	ROLE_RES_JURIDIQUE
6	ROLE_VALIDATEUR
\.


--
-- TOC entry 4919 (class 0 OID 37991)
-- Dependencies: 220
-- Data for Name: user_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_role (role_id, user_id) FROM stdin;
2	152
2	203
2	252
2	302
2	352
2	404
2	452
1	502
3	403
5	403
6	403
1	1
6	1
5	1
\.


--
-- TOC entry 4920 (class 0 OID 37994)
-- Dependencies: 221
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, cin, email, firstname, lastname, password, archiver, force_change_password) FROM stdin;
1	12345678	admin2@gmail.com	admin1	admin1	$2a$10$c47P5mwvqFsLPTRK3.a.2usaw7UVzJdCbVpvw8jo7yCT/So.2j/PC	f	f
203	14437249	sirineboussetta76@gmail.com	syrine	bousseta	$2a$10$V8/Ami9HgKR0DJy/dh1IF.XrVR/hecJNBOaErkVlORg2p5IdTAqNa	f	t
252	14437249	sirineboussettaa@gmail.com	syrine	bousseta	$2a$10$MIkTslsAMIeVDJ.Rv9zhl.jukXxvpdTTRPBZtPfba5l4F6AZjcVEG	f	f
302	14437249	sa3idsa3id@gmail.com	sa3id	ba3id	$2a$10$eGewa6HS2cCpxKcoHtyxtuZjoJM3yge26.NaNZiYbSIccmoHGC4G2	f	f
352	14437249	sala7ef@gmail.com	sal7oufa	fwz	$2a$10$gIwjtAKmX2RxgasyL1v1JuL27iMrhe6s.fPTXuwM26KoZvtig93Eu	f	f
403	14714715	ll@gmail.com	ll	dalin	$2a$10$dNDFPpBtlrzeGXF2FqYTe.HiLyscFbI/MHrrM3.AjP4grttJey8Bi	f	f
404	55240555	aa@gmail.com	mghirbi	ahmed	$2a$10$dnnjBGCQ4JeJ9BdSvNOCc.6lUswd5fxm7ycpvIg7XU39c7Amp4x7i	f	f
152	987654321	sirineboussetta71@gmail.com	syrine	bousseta	$2a$10$71t5YE48jau6FVraRoMz6.a..MChi/hKPZT2OecGDVe4JrWX5Fv.m	t	f
452	12325555	i@gmail.com	mghirbi	mg	$2a$10$55ElVWxP5g8LlJGQQnVBEOXvipd8dWkjOPAWaKiVbykYmlfPnGG/u	f	f
502	14437249	mghirbieya8@gmail.com	mghirbi	eya	$2a$10$fiP.b7fUSOLl.NuW0swubeH0RfPTyCV2abFLpuOUW2.HhfwAutp4e	f	f
\.


--
-- TOC entry 4922 (class 0 OID 38004)
-- Dependencies: 223
-- Data for Name: verfication_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.verfication_token (is_verified, expiration_time, id, user_id, token) FROM stdin;
t	2025-02-13 13:47:23.648	2	152	369157
t	2025-02-18 11:24:51.281	13	302	503670
t	2025-02-18 11:33:53.789	14	352	786407
t	2025-02-18 18:14:41.028	15	403	462402
t	2025-02-18 19:29:39.221	17	404	856428
t	2025-02-20 00:46:21.044	18	252	967159
t	2025-02-27 14:22:29.628	19	452	495401
t	2025-03-01 20:06:34.575	20	502	917781
\.


--
-- TOC entry 4928 (class 0 OID 0)
-- Dependencies: 218
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 1, false);


--
-- TOC entry 4929 (class 0 OID 0)
-- Dependencies: 217
-- Name: users_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_seq', 551, true);


--
-- TOC entry 4930 (class 0 OID 0)
-- Dependencies: 222
-- Name: verfication_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.verfication_token_id_seq', 20, true);


--
-- TOC entry 4757 (class 2606 OID 37990)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 4759 (class 2606 OID 38401)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4761 (class 2606 OID 38002)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4763 (class 2606 OID 38000)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4765 (class 2606 OID 38008)
-- Name: verfication_token verfication_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verfication_token
    ADD CONSTRAINT verfication_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4767 (class 2606 OID 38010)
-- Name: verfication_token verfication_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verfication_token
    ADD CONSTRAINT verfication_token_user_id_key UNIQUE (user_id);


--
-- TOC entry 4770 (class 2606 OID 38021)
-- Name: verfication_token fkafo4u5smbu31w38su4e5yytud; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verfication_token
    ADD CONSTRAINT fkafo4u5smbu31w38su4e5yytud FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4768 (class 2606 OID 38016)
-- Name: user_role fkj345gk1bovqvfame88rcx7yyx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4769 (class 2606 OID 38011)
-- Name: user_role fkt7e7djp752sqn6w22i6ocqy6q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkt7e7djp752sqn6w22i6ocqy6q FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


-- Completed on 2025-03-15 03:09:40

--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-03-15 03:09:40

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 37986)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    role character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 37985)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 37991)
-- Name: user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_role (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_role OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 37994)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    cin character varying(255),
    email character varying(255),
    firstname character varying(255),
    lastname character varying(255),
    password character varying(255),
    archiver boolean,
    force_change_password boolean
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 37984)
-- Name: users_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_seq OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 38004)
-- Name: verfication_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verfication_token (
    is_verified boolean NOT NULL,
    expiration_time timestamp(6) without time zone,
    id bigint NOT NULL,
    user_id bigint,
    token character varying(255)
);


ALTER TABLE public.verfication_token OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 38003)
-- Name: verfication_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.verfication_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verfication_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4918 (class 0 OID 37986)
-- Dependencies: 219
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (role_id, role) FROM stdin;
1	ROLE_ADMIN
2	ROLE_RES_COMERCIAL
3	ROLE_RES_ACHAT
4	ROLE_RES_FINANCEMENT
5	ROLE_RES_JURIDIQUE
6	ROLE_VALIDATEUR
\.


--
-- TOC entry 4919 (class 0 OID 37991)
-- Dependencies: 220
-- Data for Name: user_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_role (role_id, user_id) FROM stdin;
2	152
2	203
2	252
2	302
2	352
2	404
2	452
1	502
3	403
5	403
6	403
1	1
6	1
5	1
\.


--
-- TOC entry 4920 (class 0 OID 37994)
-- Dependencies: 221
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, cin, email, firstname, lastname, password, archiver, force_change_password) FROM stdin;
1	12345678	admin2@gmail.com	admin1	admin1	$2a$10$c47P5mwvqFsLPTRK3.a.2usaw7UVzJdCbVpvw8jo7yCT/So.2j/PC	f	f
203	14437249	sirineboussetta76@gmail.com	syrine	bousseta	$2a$10$V8/Ami9HgKR0DJy/dh1IF.XrVR/hecJNBOaErkVlORg2p5IdTAqNa	f	t
252	14437249	sirineboussettaa@gmail.com	syrine	bousseta	$2a$10$MIkTslsAMIeVDJ.Rv9zhl.jukXxvpdTTRPBZtPfba5l4F6AZjcVEG	f	f
302	14437249	sa3idsa3id@gmail.com	sa3id	ba3id	$2a$10$eGewa6HS2cCpxKcoHtyxtuZjoJM3yge26.NaNZiYbSIccmoHGC4G2	f	f
352	14437249	sala7ef@gmail.com	sal7oufa	fwz	$2a$10$gIwjtAKmX2RxgasyL1v1JuL27iMrhe6s.fPTXuwM26KoZvtig93Eu	f	f
403	14714715	ll@gmail.com	ll	dalin	$2a$10$dNDFPpBtlrzeGXF2FqYTe.HiLyscFbI/MHrrM3.AjP4grttJey8Bi	f	f
404	55240555	aa@gmail.com	mghirbi	ahmed	$2a$10$dnnjBGCQ4JeJ9BdSvNOCc.6lUswd5fxm7ycpvIg7XU39c7Amp4x7i	f	f
152	987654321	sirineboussetta71@gmail.com	syrine	bousseta	$2a$10$71t5YE48jau6FVraRoMz6.a..MChi/hKPZT2OecGDVe4JrWX5Fv.m	t	f
452	12325555	i@gmail.com	mghirbi	mg	$2a$10$55ElVWxP5g8LlJGQQnVBEOXvipd8dWkjOPAWaKiVbykYmlfPnGG/u	f	f
502	14437249	mghirbieya8@gmail.com	mghirbi	eya	$2a$10$fiP.b7fUSOLl.NuW0swubeH0RfPTyCV2abFLpuOUW2.HhfwAutp4e	f	f
\.


--
-- TOC entry 4922 (class 0 OID 38004)
-- Dependencies: 223
-- Data for Name: verfication_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.verfication_token (is_verified, expiration_time, id, user_id, token) FROM stdin;
t	2025-02-13 13:47:23.648	2	152	369157
t	2025-02-18 11:24:51.281	13	302	503670
t	2025-02-18 11:33:53.789	14	352	786407
t	2025-02-18 18:14:41.028	15	403	462402
t	2025-02-18 19:29:39.221	17	404	856428
t	2025-02-20 00:46:21.044	18	252	967159
t	2025-02-27 14:22:29.628	19	452	495401
t	2025-03-01 20:06:34.575	20	502	917781
\.


--
-- TOC entry 4928 (class 0 OID 0)
-- Dependencies: 218
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 1, false);


--
-- TOC entry 4929 (class 0 OID 0)
-- Dependencies: 217
-- Name: users_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_seq', 551, true);


--
-- TOC entry 4930 (class 0 OID 0)
-- Dependencies: 222
-- Name: verfication_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.verfication_token_id_seq', 20, true);


--
-- TOC entry 4757 (class 2606 OID 37990)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 4759 (class 2606 OID 38401)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4761 (class 2606 OID 38002)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4763 (class 2606 OID 38000)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4765 (class 2606 OID 38008)
-- Name: verfication_token verfication_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verfication_token
    ADD CONSTRAINT verfication_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4767 (class 2606 OID 38010)
-- Name: verfication_token verfication_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verfication_token
    ADD CONSTRAINT verfication_token_user_id_key UNIQUE (user_id);


--
-- TOC entry 4770 (class 2606 OID 38021)
-- Name: verfication_token fkafo4u5smbu31w38su4e5yytud; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verfication_token
    ADD CONSTRAINT fkafo4u5smbu31w38su4e5yytud FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4768 (class 2606 OID 38016)
-- Name: user_role fkj345gk1bovqvfame88rcx7yyx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4769 (class 2606 OID 38011)
-- Name: user_role fkt7e7djp752sqn6w22i6ocqy6q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkt7e7djp752sqn6w22i6ocqy6q FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


-- Completed on 2025-03-15 03:09:40

--
-- PostgreSQL database dump complete
--

